INSERT INTO levels (id, title, description) VALUES (1, 'Level 1: Cores da Natureza', 'Vamos aprender as cores básicas!');
INSERT INTO questions (level_id, type, "promptPt", "promptEn", "imageUrl", options) VALUES (1, 'association', 'Verde', 'Green', 'https://placehold.co/200x200/27ae60/27ae60?text=Green', '[{"id":1,"text":"Green","isCorrect":true},{"id":2,"text":"Blue","isCorrect":false},{"id":3,"text":"Red","isCorrect":false},{"id":4,"text":"Purple","isCorrect":false}]'::jsonb);
INSERT INTO questions (level_id, type, "promptPt", "promptEn", "imageUrl", options) VALUES (1, 'association', 'Azul', 'Blue', 'https://placehold.co/200x200/2980b9/2980b9?text=Blue', '[{"id":1,"text":"Yellow","isCorrect":false},{"id":2,"text":"Blue","isCorrect":true},{"id":3,"text":"Black","isCorrect":false},{"id":4,"text":"Purple","isCorrect":false}]'::jsonb);
INSERT INTO questions (level_id, type, "promptPt", "promptEn", "imageUrl", options) VALUES (1, 'association', 'Amarelo', 'Yellow', 'https://placehold.co/200x200/f1c40f/f1c40f?text=Yellow', '[{"id":1,"text":"White","isCorrect":false},{"id":2,"text":"Brown","isCorrect":false},{"id":3,"text":"Yellow","isCorrect":true},{"id":4,"text":"Purple","isCorrect":false}]'::jsonb);
INSERT INTO questions (level_id, type, "promptPt", "promptEn", "imageUrl", options) VALUES (1, 'association', 'Preto', 'Black', 'https://placehold.co/200x200/000000/000000?text=Black', '[{"id":1,"text":"Black","isCorrect":true},{"id":2,"text":"Pink","isCorrect":false},{"id":3,"text":"Orange","isCorrect":false},{"id":4,"text":"Purple","isCorrect":false}]'::jsonb);
INSERT INTO questions (level_id, type, "promptPt", "promptEn", "imageUrl", options) VALUES (1, 'association', 'Branco', 'White', 'https://placehold.co/200x200/ecf0f1/ecf0f1?text=White', '[{"id":1,"text":"Gray","isCorrect":false},{"id":2,"text":"White","isCorrect":true},{"id":3,"text":"Purple","isCorrect":false},{"id":4,"text":"Purple","isCorrect":false}]'::jsonb);

INSERT INTO levels (id, title, description) VALUES (2, 'Level 2: Frutas e Comidas Orgânicas', 'Comidas naturais fazem bem!');
INSERT INTO questions (level_id, type, "promptPt", "promptEn", "imageUrl", options) VALUES (2, 'translation', 'Maçã', 'Apple', '🍎', '[{"id":1,"text":"Banana","isCorrect":false},{"id":2,"text":"Apple","isCorrect":true},{"id":3,"text":"Rice","isCorrect":false},{"id":4,"text":"Meat","isCorrect":false}]'::jsonb);
INSERT INTO questions (level_id, type, "promptPt", "promptEn", "imageUrl", options) VALUES (2, 'translation', 'Banana', 'Banana', '🍌', '[{"id":1,"text":"Banana","isCorrect":true},{"id":2,"text":"Orange","isCorrect":false},{"id":3,"text":"Grape","isCorrect":false},{"id":4,"text":"Meat","isCorrect":false}]'::jsonb);
INSERT INTO questions (level_id, type, "promptPt", "promptEn", "imageUrl", options) VALUES (2, 'translation', 'Água', 'Water', '💧', '[{"id":1,"text":"Milk","isCorrect":false},{"id":2,"text":"Water","isCorrect":true},{"id":3,"text":"Grape","isCorrect":false},{"id":4,"text":"Rice","isCorrect":false}]'::jsonb);
INSERT INTO questions (level_id, type, "promptPt", "promptEn", "imageUrl", options) VALUES (2, 'translation', 'Pão', 'Bread', '🍞', '[{"id":1,"text":"Bread","isCorrect":true},{"id":2,"text":"Meat","isCorrect":false},{"id":3,"text":"Orange","isCorrect":false},{"id":4,"text":"Chicken","isCorrect":false}]'::jsonb);
INSERT INTO questions (level_id, type, "promptPt", "promptEn", "imageUrl", options) VALUES (2, 'translation', 'Peixe', 'Fish', '🐟', '[{"id":1,"text":"Chicken","isCorrect":false},{"id":2,"text":"Fish","isCorrect":true},{"id":3,"text":"Potato","isCorrect":false},{"id":4,"text":"Grape","isCorrect":false}]'::jsonb);

INSERT INTO levels (id, title, description) VALUES (3, 'Level 3: A Natureza', 'Elementos do meio ambiente');
INSERT INTO questions (level_id, type, "promptPt", "promptEn", "imageUrl", options) VALUES (3, 'association', 'Árvore', 'Tree', '🌳', '[{"id":1,"text":"Tree","isCorrect":true},{"id":2,"text":"Car","isCorrect":false},{"id":3,"text":"Moon","isCorrect":false},{"id":4,"text":"Mountain","isCorrect":false}]'::jsonb);
INSERT INTO questions (level_id, type, "promptPt", "promptEn", "imageUrl", options) VALUES (3, 'association', 'Flor', 'Flower', '🌸', '[{"id":1,"text":"House","isCorrect":false},{"id":2,"text":"Flower","isCorrect":true},{"id":3,"text":"Rock","isCorrect":false},{"id":4,"text":"Leaf","isCorrect":false}]'::jsonb);
INSERT INTO questions (level_id, type, "promptPt", "promptEn", "imageUrl", options) VALUES (3, 'association', 'Sol', 'Sun', '☀️', '[{"id":1,"text":"Moon","isCorrect":false},{"id":2,"text":"Sun","isCorrect":true},{"id":3,"text":"Star","isCorrect":false},{"id":4,"text":"Mountain","isCorrect":false}]'::jsonb);
INSERT INTO questions (level_id, type, "promptPt", "promptEn", "imageUrl", options) VALUES (3, 'association', 'Rio', 'River', '🌊', '[{"id":1,"text":"River","isCorrect":true},{"id":2,"text":"Street","isCorrect":false},{"id":3,"text":"Mountain","isCorrect":false},{"id":4,"text":"Cloud","isCorrect":false}]'::jsonb);
INSERT INTO questions (level_id, type, "promptPt", "promptEn", "imageUrl", options) VALUES (3, 'association', 'Animal', 'Animal', '🐾', '[{"id":1,"text":"Robot","isCorrect":false},{"id":2,"text":"Animal","isCorrect":true},{"id":3,"text":"Rock","isCorrect":false},{"id":4,"text":"Mountain","isCorrect":false}]'::jsonb);

INSERT INTO levels (id, title, description) VALUES (4, 'Level 4: Lixeiras da Reciclagem', 'Onde jogamos o lixo?');
INSERT INTO questions (level_id, type, "promptPt", "promptEn", "imageUrl", options) VALUES (4, 'translation', 'Papel', 'Paper', '📄', '[{"id":1,"text":"Paper","isCorrect":true},{"id":2,"text":"Glass","isCorrect":false},{"id":3,"text":"Trash","isCorrect":false},{"id":4,"text":"Rubber","isCorrect":false}]'::jsonb);
INSERT INTO questions (level_id, type, "promptPt", "promptEn", "imageUrl", options) VALUES (4, 'translation', 'Plástico', 'Plastic', '🥤', '[{"id":1,"text":"Metal","isCorrect":false},{"id":2,"text":"Plastic","isCorrect":true},{"id":3,"text":"Fabric","isCorrect":false},{"id":4,"text":"Battery","isCorrect":false}]'::jsonb);
INSERT INTO questions (level_id, type, "promptPt", "promptEn", "imageUrl", options) VALUES (4, 'translation', 'Vidro', 'Glass', '🍷', '[{"id":1,"text":"Glass","isCorrect":true},{"id":2,"text":"Paper","isCorrect":false},{"id":3,"text":"Ceramic","isCorrect":false},{"id":4,"text":"Electronic","isCorrect":false}]'::jsonb);
INSERT INTO questions (level_id, type, "promptPt", "promptEn", "imageUrl", options) VALUES (4, 'translation', 'Metal', 'Metal', '🥫', '[{"id":1,"text":"Plastic","isCorrect":false},{"id":2,"text":"Metal","isCorrect":true},{"id":3,"text":"Rubber","isCorrect":false},{"id":4,"text":"Trash","isCorrect":false}]'::jsonb);
INSERT INTO questions (level_id, type, "promptPt", "promptEn", "imageUrl", options) VALUES (4, 'translation', 'Orgânico', 'Organic', '🍂', '[{"id":1,"text":"Organic","isCorrect":true},{"id":2,"text":"Electronic","isCorrect":false},{"id":3,"text":"Battery","isCorrect":false},{"id":4,"text":"Ceramic","isCorrect":false}]'::jsonb);

INSERT INTO levels (id, title, description) VALUES (5, 'Level 5: Ações Ecológicas', 'O que devemos fazer?');
INSERT INTO questions (level_id, type, "promptPt", "promptEn", "imageUrl", options) VALUES (5, 'translation', 'Plante uma árvore', 'Plant a tree', '🌱', '[{"id":1,"text":"Cut a tree","isCorrect":false},{"id":2,"text":"Plant a tree","isCorrect":true},{"id":3,"text":"Drive a car","isCorrect":false},{"id":4,"text":"Burn trash","isCorrect":false}]'::jsonb);
INSERT INTO questions (level_id, type, "promptPt", "promptEn", "imageUrl", options) VALUES (5, 'translation', 'Economize água', 'Save water', '🚰', '[{"id":1,"text":"Waste water","isCorrect":false},{"id":2,"text":"Save water","isCorrect":true},{"id":3,"text":"Burn trash","isCorrect":false},{"id":4,"text":"Throw away","isCorrect":false}]'::jsonb);
INSERT INTO questions (level_id, type, "promptPt", "promptEn", "imageUrl", options) VALUES (5, 'translation', 'Apague a luz', 'Turn off the light', '💡', '[{"id":1,"text":"Turn on the light","isCorrect":false},{"id":2,"text":"Turn off the light","isCorrect":true},{"id":3,"text":"Burn trash","isCorrect":false},{"id":4,"text":"Waste water","isCorrect":false}]'::jsonb);
INSERT INTO questions (level_id, type, "promptPt", "promptEn", "imageUrl", options) VALUES (5, 'translation', 'Recicle', 'Recycle', '♻️', '[{"id":1,"text":"Litter","isCorrect":false},{"id":2,"text":"Recycle","isCorrect":true},{"id":3,"text":"Throw away","isCorrect":false},{"id":4,"text":"Turn on the light","isCorrect":false}]'::jsonb);
INSERT INTO questions (level_id, type, "promptPt", "promptEn", "imageUrl", options) VALUES (5, 'translation', 'Ande de bicicleta', 'Ride a bike', '🚲', '[{"id":1,"text":"Drive a car","isCorrect":false},{"id":2,"text":"Ride a bike","isCorrect":true},{"id":3,"text":"Burn trash","isCorrect":false},{"id":4,"text":"Throw away","isCorrect":false}]'::jsonb);

INSERT INTO levels (id, title, description) VALUES (6, 'Level 6: Transporte', 'Meios de transporte na cidade');
INSERT INTO questions (level_id, type, "promptPt", "promptEn", "imageUrl", options) VALUES (6, 'translation', 'Ônibus', 'Bus', '🚌', '[{"id":1,"text":"Bus","isCorrect":true},{"id":2,"text":"Train","isCorrect":false},{"id":3,"text":"Skateboard","isCorrect":false},{"id":4,"text":"Motorcycle","isCorrect":false}]'::jsonb);
INSERT INTO questions (level_id, type, "promptPt", "promptEn", "imageUrl", options) VALUES (6, 'translation', 'Bicicleta', 'Bicycle', '🚲', '[{"id":1,"text":"Bicycle","isCorrect":true},{"id":2,"text":"Car","isCorrect":false},{"id":3,"text":"Truck","isCorrect":false},{"id":4,"text":"Skateboard","isCorrect":false}]'::jsonb);
INSERT INTO questions (level_id, type, "promptPt", "promptEn", "imageUrl", options) VALUES (6, 'translation', 'Carro', 'Car', '🚗', '[{"id":1,"text":"Bus","isCorrect":false},{"id":2,"text":"Car","isCorrect":true},{"id":3,"text":"Helicopter","isCorrect":false},{"id":4,"text":"Truck","isCorrect":false}]'::jsonb);
INSERT INTO questions (level_id, type, "promptPt", "promptEn", "imageUrl", options) VALUES (6, 'translation', 'Trem', 'Train', '🚂', '[{"id":1,"text":"Train","isCorrect":true},{"id":2,"text":"Airplane","isCorrect":false},{"id":3,"text":"Helicopter","isCorrect":false},{"id":4,"text":"Truck","isCorrect":false}]'::jsonb);
INSERT INTO questions (level_id, type, "promptPt", "promptEn", "imageUrl", options) VALUES (6, 'translation', 'Andar a pé', 'Walking', '🚶', '[{"id":1,"text":"Running","isCorrect":false},{"id":2,"text":"Walking","isCorrect":true},{"id":3,"text":"Skateboard","isCorrect":false},{"id":4,"text":"Scooter","isCorrect":false}]'::jsonb);

INSERT INTO levels (id, title, description) VALUES (7, 'Level 7: Energia Limpa', 'Fontes de energia renováveis');
INSERT INTO questions (level_id, type, "promptPt", "promptEn", "imageUrl", options) VALUES (7, 'translation', 'Painel Solar', 'Solar panel', '☀️', '[{"id":1,"text":"Wind turbine","isCorrect":false},{"id":2,"text":"Solar panel","isCorrect":true},{"id":3,"text":"Gas","isCorrect":false},{"id":4,"text":"Diesel","isCorrect":false}]'::jsonb);
INSERT INTO questions (level_id, type, "promptPt", "promptEn", "imageUrl", options) VALUES (7, 'translation', 'Turbina Eólica', 'Wind turbine', '🌬️', '[{"id":1,"text":"Solar panel","isCorrect":false},{"id":2,"text":"Wind turbine","isCorrect":true},{"id":3,"text":"Coal","isCorrect":false},{"id":4,"text":"Diesel","isCorrect":false}]'::jsonb);
INSERT INTO questions (level_id, type, "promptPt", "promptEn", "imageUrl", options) VALUES (7, 'translation', 'Eletricidade', 'Electricity', '⚡', '[{"id":1,"text":"Electricity","isCorrect":true},{"id":2,"text":"Fire","isCorrect":false},{"id":3,"text":"Smoke","isCorrect":false},{"id":4,"text":"Gasoline","isCorrect":false}]'::jsonb);
INSERT INTO questions (level_id, type, "promptPt", "promptEn", "imageUrl", options) VALUES (7, 'translation', 'Lâmpada', 'Lightbulb', '💡', '[{"id":1,"text":"Candle","isCorrect":false},{"id":2,"text":"Lightbulb","isCorrect":true},{"id":3,"text":"Fire","isCorrect":false},{"id":4,"text":"Oil","isCorrect":false}]'::jsonb);
INSERT INTO questions (level_id, type, "promptPt", "promptEn", "imageUrl", options) VALUES (7, 'translation', 'Bateria', 'Battery', '🔋', '[{"id":1,"text":"Battery","isCorrect":true},{"id":2,"text":"Wire","isCorrect":false},{"id":3,"text":"Smoke","isCorrect":false},{"id":4,"text":"Fire","isCorrect":false}]'::jsonb);

INSERT INTO levels (id, title, description) VALUES (8, 'Level 8: Verbos de Ação', 'Ações do dia a dia');
INSERT INTO questions (level_id, type, "promptPt", "promptEn", "imageUrl", options) VALUES (8, 'translation', 'Ser / Estar', 'To be', '👤', '[{"id":1,"text":"To be","isCorrect":true},{"id":2,"text":"To go","isCorrect":false},{"id":3,"text":"To stop","isCorrect":false},{"id":4,"text":"To eat","isCorrect":false}]'::jsonb);
INSERT INTO questions (level_id, type, "promptPt", "promptEn", "imageUrl", options) VALUES (8, 'translation', 'Ter', 'To have', '🤲', '[{"id":1,"text":"To make","isCorrect":false},{"id":2,"text":"To have","isCorrect":true},{"id":3,"text":"To stop","isCorrect":false},{"id":4,"text":"To jump","isCorrect":false}]'::jsonb);
INSERT INTO questions (level_id, type, "promptPt", "promptEn", "imageUrl", options) VALUES (8, 'translation', 'Fazer (ação)', 'To do', '🛠️', '[{"id":1,"text":"To do","isCorrect":true},{"id":2,"text":"To stop","isCorrect":false},{"id":3,"text":"To jump","isCorrect":false},{"id":4,"text":"To sleep","isCorrect":false}]'::jsonb);
INSERT INTO questions (level_id, type, "promptPt", "promptEn", "imageUrl", options) VALUES (8, 'translation', 'Fazer (criar)', 'To make', '🎨', '[{"id":1,"text":"To have","isCorrect":false},{"id":2,"text":"To make","isCorrect":true},{"id":3,"text":"To jump","isCorrect":false},{"id":4,"text":"To run","isCorrect":false}]'::jsonb);
INSERT INTO questions (level_id, type, "promptPt", "promptEn", "imageUrl", options) VALUES (8, 'translation', 'Ir', 'To go', '🚶', '[{"id":1,"text":"To come","isCorrect":false},{"id":2,"text":"To go","isCorrect":true},{"id":3,"text":"To stop","isCorrect":false},{"id":4,"text":"To run","isCorrect":false}]'::jsonb);

INSERT INTO levels (id, title, description) VALUES (9, 'Level 9: Verbo To Be e Sustentabilidade', 'O verbo To Be aplicado!');
INSERT INTO questions (level_id, type, "promptPt", "promptEn", "imageUrl", options) VALUES (9, 'sentence', 'Eu sou ecológico', 'I am eco-friendly', '🌍', '[{"id":1,"text":"I am eco-friendly","isCorrect":true},{"id":2,"text":"You are eco-friendly","isCorrect":false},{"id":3,"text":"You are a villain","isCorrect":false},{"id":4,"text":"They are divided","isCorrect":false}]'::jsonb);
INSERT INTO questions (level_id, type, "promptPt", "promptEn", "imageUrl", options) VALUES (9, 'sentence', 'A água é limpa', 'The water is clean', '💧', '[{"id":1,"text":"The water is dirty","isCorrect":false},{"id":2,"text":"The water is clean","isCorrect":true},{"id":3,"text":"I am a monster","isCorrect":false},{"id":4,"text":"It is a rock","isCorrect":false}]'::jsonb);
INSERT INTO questions (level_id, type, "promptPt", "promptEn", "imageUrl", options) VALUES (9, 'sentence', 'Nós somos unidos', 'We are united', '🤝', '[{"id":1,"text":"We are united","isCorrect":true},{"id":2,"text":"They are united","isCorrect":false},{"id":3,"text":"The water is dirty","isCorrect":false},{"id":4,"text":"I am a monster","isCorrect":false}]'::jsonb);
INSERT INTO questions (level_id, type, "promptPt", "promptEn", "imageUrl", options) VALUES (9, 'sentence', 'Isto é uma árvore', 'It is a tree', '🌳', '[{"id":1,"text":"It is a car","isCorrect":false},{"id":2,"text":"It is a tree","isCorrect":true},{"id":3,"text":"The water is dirty","isCorrect":false},{"id":4,"text":"I hate nature","isCorrect":false}]'::jsonb);
INSERT INTO questions (level_id, type, "promptPt", "promptEn", "imageUrl", options) VALUES (9, 'sentence', 'Você é um guardião', 'You are a guardian', '🛡️', '[{"id":1,"text":"I am a guardian","isCorrect":false},{"id":2,"text":"You are a guardian","isCorrect":true},{"id":3,"text":"The water is dirty","isCorrect":false},{"id":4,"text":"I am a monster","isCorrect":false}]'::jsonb);

INSERT INTO levels (id, title, description) VALUES (10, 'Level 10: Adjetivos', 'Qualidades e defeitos');
INSERT INTO questions (level_id, type, "promptPt", "promptEn", "imageUrl", options) VALUES (10, 'translation', 'Limpo', 'Clean', '✨', '[{"id":1,"text":"Clean","isCorrect":true},{"id":2,"text":"Dirty","isCorrect":false},{"id":3,"text":"Slow","isCorrect":false},{"id":4,"text":"Happy","isCorrect":false}]'::jsonb);
INSERT INTO questions (level_id, type, "promptPt", "promptEn", "imageUrl", options) VALUES (10, 'translation', 'Sujo', 'Dirty', '🗑️', '[{"id":1,"text":"Clean","isCorrect":false},{"id":2,"text":"Dirty","isCorrect":true},{"id":3,"text":"Dark","isCorrect":false},{"id":4,"text":"Light","isCorrect":false}]'::jsonb);
INSERT INTO questions (level_id, type, "promptPt", "promptEn", "imageUrl", options) VALUES (10, 'translation', 'Grande', 'Big', '🐘', '[{"id":1,"text":"Small","isCorrect":false},{"id":2,"text":"Big","isCorrect":true},{"id":3,"text":"Blue","isCorrect":false},{"id":4,"text":"Dark","isCorrect":false}]'::jsonb);
INSERT INTO questions (level_id, type, "promptPt", "promptEn", "imageUrl", options) VALUES (10, 'translation', 'Pequeno', 'Small', '🐜', '[{"id":1,"text":"Small","isCorrect":true},{"id":2,"text":"Big","isCorrect":false},{"id":3,"text":"Fast","isCorrect":false},{"id":4,"text":"Heavy","isCorrect":false}]'::jsonb);
INSERT INTO questions (level_id, type, "promptPt", "promptEn", "imageUrl", options) VALUES (10, 'translation', 'Verde (ecológico)', 'Green', '🌿', '[{"id":1,"text":"Green","isCorrect":true},{"id":2,"text":"Gray","isCorrect":false},{"id":3,"text":"Sad","isCorrect":false},{"id":4,"text":"Red","isCorrect":false}]'::jsonb);

INSERT INTO levels (id, title, description) VALUES (11, 'Level 11: Locais da Cidade', 'Nossa cidade');
INSERT INTO questions (level_id, type, "promptPt", "promptEn", "imageUrl", options) VALUES (11, 'translation', 'Parque', 'Park', '🏞️', '[{"id":1,"text":"Park","isCorrect":true},{"id":2,"text":"Mall","isCorrect":false},{"id":3,"text":"Bank","isCorrect":false},{"id":4,"text":"Cinema","isCorrect":false}]'::jsonb);
INSERT INTO questions (level_id, type, "promptPt", "promptEn", "imageUrl", options) VALUES (11, 'translation', 'Rua', 'Street', '🛣️', '[{"id":1,"text":"House","isCorrect":false},{"id":2,"text":"Street","isCorrect":true},{"id":3,"text":"Mall","isCorrect":false},{"id":4,"text":"Hospital","isCorrect":false}]'::jsonb);
INSERT INTO questions (level_id, type, "promptPt", "promptEn", "imageUrl", options) VALUES (11, 'translation', 'Casa', 'House', '🏠', '[{"id":1,"text":"School","isCorrect":false},{"id":2,"text":"House","isCorrect":true},{"id":3,"text":"Bank","isCorrect":false},{"id":4,"text":"Gym","isCorrect":false}]'::jsonb);
INSERT INTO questions (level_id, type, "promptPt", "promptEn", "imageUrl", options) VALUES (11, 'translation', 'Escola', 'School', '🏫', '[{"id":1,"text":"School","isCorrect":true},{"id":2,"text":"Park","isCorrect":false},{"id":3,"text":"Cinema","isCorrect":false},{"id":4,"text":"Hospital","isCorrect":false}]'::jsonb);
INSERT INTO questions (level_id, type, "promptPt", "promptEn", "imageUrl", options) VALUES (11, 'translation', 'Praia', 'Beach', '🏖️', '[{"id":1,"text":"Mountain","isCorrect":false},{"id":2,"text":"Beach","isCorrect":true},{"id":3,"text":"Hospital","isCorrect":false},{"id":4,"text":"Supermarket","isCorrect":false}]'::jsonb);

INSERT INTO levels (id, title, description) VALUES (12, 'Level 12: Clima', 'Como está o tempo?');
INSERT INTO questions (level_id, type, "promptPt", "promptEn", "imageUrl", options) VALUES (12, 'translation', 'Ensolarado', 'Sunny', '☀️', '[{"id":1,"text":"Rainy","isCorrect":false},{"id":2,"text":"Sunny","isCorrect":true},{"id":3,"text":"Dry","isCorrect":false},{"id":4,"text":"Stormy","isCorrect":false}]'::jsonb);
INSERT INTO questions (level_id, type, "promptPt", "promptEn", "imageUrl", options) VALUES (12, 'translation', 'Chuvoso', 'Rainy', '🌧️', '[{"id":1,"text":"Sunny","isCorrect":false},{"id":2,"text":"Rainy","isCorrect":true},{"id":3,"text":"Clear","isCorrect":false},{"id":4,"text":"Freezing","isCorrect":false}]'::jsonb);
INSERT INTO questions (level_id, type, "promptPt", "promptEn", "imageUrl", options) VALUES (12, 'translation', 'Nublado', 'Cloudy', '☁️', '[{"id":1,"text":"Cloudy","isCorrect":true},{"id":2,"text":"Windy","isCorrect":false},{"id":3,"text":"Foggy","isCorrect":false},{"id":4,"text":"Cold","isCorrect":false}]'::jsonb);
INSERT INTO questions (level_id, type, "promptPt", "promptEn", "imageUrl", options) VALUES (12, 'translation', 'Ventoso', 'Windy', '🌬️', '[{"id":1,"text":"Windy","isCorrect":true},{"id":2,"text":"Sunny","isCorrect":false},{"id":3,"text":"Freezing","isCorrect":false},{"id":4,"text":"Snowing","isCorrect":false}]'::jsonb);
INSERT INTO questions (level_id, type, "promptPt", "promptEn", "imageUrl", options) VALUES (12, 'translation', 'Quente', 'Hot', '🌡️', '[{"id":1,"text":"Cold","isCorrect":false},{"id":2,"text":"Hot","isCorrect":true},{"id":3,"text":"Freezing","isCorrect":false},{"id":4,"text":"Clear","isCorrect":false}]'::jsonb);

INSERT INTO levels (id, title, description) VALUES (13, 'Level 13: Frases Curtas 1', 'Juntando as palavras');
INSERT INTO questions (level_id, type, "promptPt", "promptEn", "imageUrl", options) VALUES (13, 'sentence', 'O parque é limpo', 'The park is clean', '🏞️', '[{"id":1,"text":"The park is clean","isCorrect":true},{"id":2,"text":"The park is dirty","isCorrect":false},{"id":3,"text":"The sky is green","isCorrect":false},{"id":4,"text":"We waste water","isCorrect":false}]'::jsonb);
INSERT INTO questions (level_id, type, "promptPt", "promptEn", "imageUrl", options) VALUES (13, 'sentence', 'Eu reciclo plástico', 'I recycle plastic', '♻️', '[{"id":1,"text":"I recycle paper","isCorrect":false},{"id":2,"text":"I recycle plastic","isCorrect":true},{"id":3,"text":"The sky is green","isCorrect":false},{"id":4,"text":"The sun is cold","isCorrect":false}]'::jsonb);
INSERT INTO questions (level_id, type, "promptPt", "promptEn", "imageUrl", options) VALUES (13, 'sentence', 'Nós economizamos água', 'We save water', '🚰', '[{"id":1,"text":"We waste water","isCorrect":false},{"id":2,"text":"We save water","isCorrect":true},{"id":3,"text":"The park is dirty","isCorrect":false},{"id":4,"text":"Turn on the light","isCorrect":false}]'::jsonb);
INSERT INTO questions (level_id, type, "promptPt", "promptEn", "imageUrl", options) VALUES (13, 'sentence', 'O sol é quente', 'The sun is hot', 'https://hkddkejyzdvepdlhadlf.supabase.co/storage/v1/object/public/imagens%20exercicios/level%2013/1304S.jpeg', '[{"id":1,"text":"The moon is cold","isCorrect":false},{"id":2,"text":"The sun is hot","isCorrect":true},{"id":3,"text":"I throw plastic","isCorrect":false},{"id":4,"text":"The sky is green","isCorrect":false}]'::jsonb);
INSERT INTO questions (level_id, type, "promptPt", "promptEn", "imageUrl", options) VALUES (13, 'sentence', 'Apague a luz', 'Turn off the light', 'https://hkddkejyzdvepdlhadlf.supabase.co/storage/v1/object/public/imagens%20exercicios/level%2013/1305.jpeg', '[{"id":1,"text":"Turn on the light","isCorrect":false},{"id":2,"text":"Turn off the light","isCorrect":true},{"id":3,"text":"The sky is green","isCorrect":false},{"id":4,"text":"I throw plastic","isCorrect":false}]'::jsonb);

INSERT INTO levels (id, title, description) VALUES (14, 'Level 14: Frases Curtas 2', 'Expressões ambientais');
INSERT INTO questions (level_id, type, "promptPt", "promptEn", "imageUrl", options) VALUES (14, 'sentence', 'Plantar uma árvore é bom', 'Planting a tree is good', '🌳', '[{"id":1,"text":"Planting a tree is bad","isCorrect":false},{"id":2,"text":"Planting a tree is good","isCorrect":true},{"id":3,"text":"Throw trash","isCorrect":false},{"id":4,"text":"Use a car","isCorrect":false}]'::jsonb);
INSERT INTO questions (level_id, type, "promptPt", "promptEn", "imageUrl", options) VALUES (14, 'sentence', 'Não jogue lixo', 'Do not litter', '🗑️', '[{"id":1,"text":"Litter here","isCorrect":false},{"id":2,"text":"Do not litter","isCorrect":true},{"id":3,"text":"Use a car","isCorrect":false},{"id":4,"text":"The river is green","isCorrect":false}]'::jsonb);
INSERT INTO questions (level_id, type, "promptPt", "promptEn", "imageUrl", options) VALUES (14, 'sentence', 'Use uma bicicleta', 'Use a bicycle', '🚲', '[{"id":1,"text":"Use a car","isCorrect":false},{"id":2,"text":"Use a bicycle","isCorrect":true},{"id":3,"text":"The river is green","isCorrect":false},{"id":4,"text":"Cutting a tree is good","isCorrect":false}]'::jsonb);
INSERT INTO questions (level_id, type, "promptPt", "promptEn", "imageUrl", options) VALUES (14, 'sentence', 'O rio é azul', 'The river is blue', '🌊', '[{"id":1,"text":"The river is blue","isCorrect":true},{"id":2,"text":"The river is green","isCorrect":false},{"id":3,"text":"The ocean is dry","isCorrect":false},{"id":4,"text":"Cutting a tree is good","isCorrect":false}]'::jsonb);
INSERT INTO questions (level_id, type, "promptPt", "promptEn", "imageUrl", options) VALUES (14, 'sentence', 'Nós somos felizes', 'We are happy', '😊', '[{"id":1,"text":"We are sad","isCorrect":false},{"id":2,"text":"We are happy","isCorrect":true},{"id":3,"text":"Cutting a tree is good","isCorrect":false},{"id":4,"text":"The river is green","isCorrect":false}]'::jsonb);

INSERT INTO levels (id, title, description) VALUES (15, 'Level 15: O Desafio Final!', 'Prove que você é um Guardião Eco-Bilingue!');
INSERT INTO questions (level_id, type, "promptPt", "promptEn", "imageUrl", options) VALUES (15, 'sentence', 'Eu sou um guardião', 'I am a guardian', '🛡️', '[{"id":1,"text":"I am a guardian","isCorrect":true},{"id":2,"text":"I am a monster","isCorrect":false},{"id":3,"text":"Dirty energy is the future","isCorrect":false},{"id":4,"text":"Waste everything","isCorrect":false}]'::jsonb);
INSERT INTO questions (level_id, type, "promptPt", "promptEn", "imageUrl", options) VALUES (15, 'sentence', 'Nós protegemos o planeta', 'We protect the planet', '🌍', '[{"id":1,"text":"We destroy the planet","isCorrect":false},{"id":2,"text":"We protect the planet","isCorrect":true},{"id":3,"text":"I am a villain","isCorrect":false},{"id":4,"text":"Dirty energy is the future","isCorrect":false}]'::jsonb);
INSERT INTO questions (level_id, type, "promptPt", "promptEn", "imageUrl", options) VALUES (15, 'sentence', 'Energia limpa é o futuro', 'Clean energy is the future', '⚡', '[{"id":1,"text":"Clean energy is the future","isCorrect":true},{"id":2,"text":"Dirty energy is the future","isCorrect":false},{"id":3,"text":"Waste everything","isCorrect":false},{"id":4,"text":"Destroy the world!","isCorrect":false}]'::jsonb);
INSERT INTO questions (level_id, type, "promptPt", "promptEn", "imageUrl", options) VALUES (15, 'sentence', 'Recicle todos os dias', 'Recycle every day', '♻️', '[{"id":1,"text":"Recycle every year","isCorrect":false},{"id":2,"text":"Recycle every day","isCorrect":true},{"id":3,"text":"Dirty energy is the future","isCorrect":false},{"id":4,"text":"Destroy the world!","isCorrect":false}]'::jsonb);
INSERT INTO questions (level_id, type, "promptPt", "promptEn", "imageUrl", options) VALUES (15, 'sentence', 'Salve o mundo!', 'Save the world!', '🦸', '[{"id":1,"text":"Save the world!","isCorrect":true},{"id":2,"text":"Destroy the world!","isCorrect":false},{"id":3,"text":"Waste everything","isCorrect":false},{"id":4,"text":"We destroy the planet","isCorrect":false}]'::jsonb);

